export const NEWS_REQUEST_START = 'NEWS_REQUEST_START'
export const NEWS_REQUEST_SUCCESS = 'NEWS_REQUEST_SUCESS'
export const NEWS_REQUEST_FAILURE = 'NEWS_REQUEST_FAILURE'
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER'
