export const SCHEDULE_REQUEST_START = 'SCHEDULE_REQUEST_START'
export const SCHEDULE_REQUEST_SUCCESS = 'SCHEDULE_REQUEST_SUCCESS'
export const SCHEDULE_REQUEST_FAILURE = 'SCHEDULE_REQUEST_FAILURE'
export const SET_WEEK = 'SET_WEEK'
